version: '3'
services:

  app:
    image: ipreplay/development
    container_name: ipreplay_development_1
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080
      - 5000:5000
    command: bash -c "npm install; npm run dev"
    volumes:
      - .:/app
    links:
      - dynamodb
      - dynamodbtest
    environment:
      AWS_ACCESS_KEY_ID: REPLACE_ADD_TO_RUN_TESTS_IN_DOCKER
      AWS_SECRET_ACCESS_KEY: REPLACE_ADD_TO_RUN_TESTS_IN_DOCKER
      AWS_SERVERLESS_SERVICE: REPLACE_ADD_TO_RUN_TESTS_IN_DOCKER
      AWS_REGION: REPLACE_ADD_TO_RUN_TESTS_IN_DOCKER
      DYNAMO_LOCAL_URL: http://dynamodb:8000
      DYNAMO_LOCAL_TEST_URL: http://dynamodbtest:8000

  dynamodb:
    image: dwmkerr/dynamodb
    ports:
      - 8000:8000
    volumes:
      - ./etc/dynamo:/data/
    command: -dbPath /data/

  dynamodbtest:
    image: dwmkerr/dynamodb
    ports:
      - 8001:8000
