import { IMetricsFilterAddon } from "."
import * as mappings from './marks'
/**
 * @desc List of known browsers
 * @requires clientsdk library on installed on client application to use this patterns.
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html
 **/

export const BrowsersAll = [{ label: "Browsers All", metricFilter: { path: ["event"], value: mappings.MARK.SessionDataHardware }, id: "browser:all" }]

// export const Browsers: IMetricsFilterAddon[] = [{ label: "Browser Amaya", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Amaya" }, id: "browser:amaya" },
// { label: "Browser Android Browser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Android Browser" }, id: "browser:android:browser" },
// { label: "Browser Arora", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Arora" }, id: "browser:arora" },
// { label: "Browser Avant", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Avant" }, id: "browser:avant" },
// { label: "Browser Baidu", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Baidu" }, id: "browser:baidu" },
// { label: "Browser Blazer", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Blazer" }, id: "browser:blazer" },
// { label: "Browser Bolt", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Bolt" }, id: "browser:bolt" },
// { label: "Browser Bowser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Bowser" }, id: "browser:bowser" },
// { label: "Browser Camino", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Camino" }, id: "browser:camino" },
// { label: "Browser Chimera", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Chimera" }, id: "browser:chimera" },
// { label: "Browser Chrome [WebView]", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Chrome [WebView]" }, id: "browser:chrome:[webview]" },
// { label: "Browser Chromium", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Chromium" }, id: "browser:chromium" },
// { label: "Browser Comodo Dragon", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Comodo Dragon" }, id: "browser:comodo:dragon" },
// { label: "Browser Conkeror", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Conkeror" }, id: "browser:conkeror" },
// { label: "Browser Dillo", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Dillo" }, id: "browser:dillo" },
// { label: "Browser Dolphin", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Dolphin" }, id: "browser:dolphin" },
// { label: "Browser Doris", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Doris" }, id: "browser:doris" },
// { label: "Browser Edge", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Edge" }, id: "browser:edge" },
// { label: "Browser Epiphany", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Epiphany" }, id: "browser:epiphany" },
// { label: "Browser Fennec", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Fennec" }, id: "browser:fennec" },
// { label: "Browser Firebird", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Firebird" }, id: "browser:firebird" },
// { label: "Browser Firefox", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Firefox" }, id: "browser:firefox" },
// { label: "Browser Flock", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Flock" }, id: "browser:flock" },
// { label: "Browser GoBrowser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "GoBrowser" }, id: "browser:gobrowser" },
// { label: "Browser iCab", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "iCab" }, id: "browser:icab" },
// { label: "Browser ICE Browser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "ICE Browser" }, id: "browser:ice:browser" },
// { label: "Browser IceApe", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "IceApe" }, id: "browser:iceape" },
// { label: "Browser IceCat", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "IceCat" }, id: "browser:icecat" },
// { label: "Browser IceDragon", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "IceDragon" }, id: "browser:icedragon" },
// { label: "Browser Iceweasel", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Iceweasel" }, id: "browser:iceweasel" },
// { label: "Browser IE[Mobile]", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "IE[Mobile]" }, id: "browser:ie[mobile]" },
// { label: "Browser Iron", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Iron" }, id: "browser:iron" },
// { label: "Browser Jasmine", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Jasmine" }, id: "browser:jasmine" },
// { label: "Browser K-Meleon", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "K-Meleon" }, id: "browser:k-meleon" },
// { label: "Browser Konqueror", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Konqueror" }, id: "browser:konqueror" },
// { label: "Browser Kindle", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Kindle" }, id: "browser:kindle" },
// { label: "Browser Links", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Links" }, id: "browser:links" },
// { label: "Browser Lunascape", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Lunascape" }, id: "browser:lunascape" },
// { label: "Browser Lynx", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Lynx" }, id: "browser:lynx" },
// { label: "Browser Maemo", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Maemo" }, id: "browser:maemo" },
// { label: "Browser Maxthon", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Maxthon" }, id: "browser:maxthon" },
// { label: "Browser Midori", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Midori" }, id: "browser:midori" },
// { label: "Browser Minimo", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Minimo" }, id: "browser:minimo" },
// { label: "Browser MIUI Browser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "MIUI Browser" }, id: "browser:miui:browser" },
// { label: "Browser [Mobile] Safari", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "[Mobile] Safari" }, id: "browser:[mobile]:safari" },
// { label: "Browser Mosaic", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Mosaic" }, id: "browser:mosaic" },
// { label: "Browser Mozilla", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Mozilla" }, id: "browser:mozilla" },
// { label: "Browser Netfront", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Netfront" }, id: "browser:netfront" },
// { label: "Browser Netscape", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Netscape" }, id: "browser:netscape" },
// { label: "Browser NetSurf", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "NetSurf" }, id: "browser:netsurf" },
// { label: "Browser Nokia", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Nokia" }, id: "browser:nokia" },
// { label: "Browser OmniWeb", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "OmniWeb" }, id: "browser:omniweb" },
// { label: "Browser Opera [Mini/Mobi/Tablet]", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Opera [Mini/Mobi/Tablet]" }, id: "browser:opera:[mini/mobi/tablet]" },
// { label: "Browser PhantomJS", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "PhantomJS" }, id: "browser:phantomjs" },
// { label: "Browser Phoenix", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Phoenix" }, id: "browser:phoenix" },
// { label: "Browser Polaris", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Polaris" }, id: "browser:polaris" },
// { label: "Browser QQBrowser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "QQBrowser" }, id: "browser:qqbrowser" },
// { label: "Browser QQBrowserLite", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "QQBrowserLite" }, id: "browser:qqbrowserlite" },
// { label: "Browser Quark", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Quark" }, id: "browser:quark" },
// { label: "Browser RockMelt", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "RockMelt" }, id: "browser:rockmelt" },
// { label: "Browser Silk", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Silk" }, id: "browser:silk" },
// { label: "Browser Skyfire", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Skyfire" }, id: "browser:skyfire" },
// { label: "Browser SeaMonkey", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "SeaMonkey" }, id: "browser:seamonkey" },
// { label: "Browser Sleipnir", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Sleipnir" }, id: "browser:sleipnir" },
// { label: "Browser SlimBrowser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "SlimBrowser" }, id: "browser:slimbrowser" },
// { label: "Browser Swiftfox", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Swiftfox" }, id: "browser:swiftfox" },
// { label: "Browser Tizen", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Tizen" }, id: "browser:tizen" },
// { label: "Browser UCBrowser", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "UCBrowser" }, id: "browser:ucbrowser" },
// { label: "Browser Vivaldi", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Vivaldi" }, id: "browser:vivaldi" },
// { label: "Browser w3m", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "w3m" }, id: "browser:w3m" },
// { label: "Browser Waterfox", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Waterfox" }, id: "browser:waterfox" },
// { label: "Browser WeChat", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "WeChat" }, id: "browser:wechat" },
// { label: "Browser Yandex", metricFilter: { path: ["payload", "userAgent", "browser", "name"], value: "Yandex" }, id: "browser:yandex" }]