import { IMetricsFilterAddon } from ".";

/**
 * @desc List of known browsers
 * @requires clientsdk library on installed on client application to use this patterns.
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html
 **/
export const Browsers: IMetricsFilterAddon[] = [{ label: "Browser Amaya", pattern: "{$.payload.userAgent.browser.name = \"Amaya\"}", id: "browser:amaya" },
{ label: "Browser Android Browser", pattern: "{$.payload.userAgent.browser.name = \"Android Browser\"}", id: "browser:android:browser" },
{ label: "Browser Arora", pattern: "{$.payload.userAgent.browser.name = \"Arora\"}", id: "browser:arora" },
{ label: "Browser Avant", pattern: "{$.payload.userAgent.browser.name = \"Avant\"}", id: "browser:avant" },
{ label: "Browser Baidu", pattern: "{$.payload.userAgent.browser.name = \"Baidu\"}", id: "browser:baidu" },
{ label: "Browser Blazer", pattern: "{$.payload.userAgent.browser.name = \"Blazer\"}", id: "browser:blazer" },
{ label: "Browser Bolt", pattern: "{$.payload.userAgent.browser.name = \"Bolt\"}", id: "browser:bolt" },
{ label: "Browser Bowser", pattern: "{$.payload.userAgent.browser.name = \"Bowser\"}", id: "browser:bowser" },
{ label: "Browser Camino", pattern: "{$.payload.userAgent.browser.name = \"Camino\"}", id: "browser:camino" },
{ label: "Browser Chimera", pattern: "{$.payload.userAgent.browser.name = \"Chimera\"}", id: "browser:chimera" },
{ label: "Browser Chrome [WebView]", pattern: "{$.payload.userAgent.browser.name = \"Chrome [WebView]\"}", id: "browser:chrome:[webview]" },
{ label: "Browser Chromium", pattern: "{$.payload.userAgent.browser.name = \"Chromium\"}", id: "browser:chromium" },
{ label: "Browser Comodo Dragon", pattern: "{$.payload.userAgent.browser.name = \"Comodo Dragon\"}", id: "browser:comodo:dragon" },
{ label: "Browser Conkeror", pattern: "{$.payload.userAgent.browser.name = \"Conkeror\"}", id: "browser:conkeror" },
{ label: "Browser Dillo", pattern: "{$.payload.userAgent.browser.name = \"Dillo\"}", id: "browser:dillo" },
{ label: "Browser Dolphin", pattern: "{$.payload.userAgent.browser.name = \"Dolphin\"}", id: "browser:dolphin" },
{ label: "Browser Doris", pattern: "{$.payload.userAgent.browser.name = \"Doris\"}", id: "browser:doris" },
{ label: "Browser Edge", pattern: "{$.payload.userAgent.browser.name = \"Edge\"}", id: "browser:edge" },
{ label: "Browser Epiphany", pattern: "{$.payload.userAgent.browser.name = \"Epiphany\"}", id: "browser:epiphany" },
{ label: "Browser Fennec", pattern: "{$.payload.userAgent.browser.name = \"Fennec\"}", id: "browser:fennec" },
{ label: "Browser Firebird", pattern: "{$.payload.userAgent.browser.name = \"Firebird\"}", id: "browser:firebird" },
{ label: "Browser Firefox", pattern: "{$.payload.userAgent.browser.name = \"Firefox\"}", id: "browser:firefox" },
{ label: "Browser Flock", pattern: "{$.payload.userAgent.browser.name = \"Flock\"}", id: "browser:flock" },
{ label: "Browser GoBrowser", pattern: "{$.payload.userAgent.browser.name = \"GoBrowser\"}", id: "browser:gobrowser" },
{ label: "Browser iCab", pattern: "{$.payload.userAgent.browser.name = \"iCab\"}", id: "browser:icab" },
{ label: "Browser ICE Browser", pattern: "{$.payload.userAgent.browser.name = \"ICE Browser\"}", id: "browser:ice:browser" },
{ label: "Browser IceApe", pattern: "{$.payload.userAgent.browser.name = \"IceApe\"}", id: "browser:iceape" },
{ label: "Browser IceCat", pattern: "{$.payload.userAgent.browser.name = \"IceCat\"}", id: "browser:icecat" },
{ label: "Browser IceDragon", pattern: "{$.payload.userAgent.browser.name = \"IceDragon\"}", id: "browser:icedragon" },
{ label: "Browser Iceweasel", pattern: "{$.payload.userAgent.browser.name = \"Iceweasel\"}", id: "browser:iceweasel" },
{ label: "Browser IE[Mobile]", pattern: "{$.payload.userAgent.browser.name = \"IE[Mobile]\"}", id: "browser:ie[mobile]" },
{ label: "Browser Iron", pattern: "{$.payload.userAgent.browser.name = \"Iron\"}", id: "browser:iron" },
{ label: "Browser Jasmine", pattern: "{$.payload.userAgent.browser.name = \"Jasmine\"}", id: "browser:jasmine" },
{ label: "Browser K-Meleon", pattern: "{$.payload.userAgent.browser.name = \"K-Meleon\"}", id: "browser:k-meleon" },
{ label: "Browser Konqueror", pattern: "{$.payload.userAgent.browser.name = \"Konqueror\"}", id: "browser:konqueror" },
{ label: "Browser Kindle", pattern: "{$.payload.userAgent.browser.name = \"Kindle\"}", id: "browser:kindle" },
{ label: "Browser Links", pattern: "{$.payload.userAgent.browser.name = \"Links\"}", id: "browser:links" },
{ label: "Browser Lunascape", pattern: "{$.payload.userAgent.browser.name = \"Lunascape\"}", id: "browser:lunascape" },
{ label: "Browser Lynx", pattern: "{$.payload.userAgent.browser.name = \"Lynx\"}", id: "browser:lynx" },
{ label: "Browser Maemo", pattern: "{$.payload.userAgent.browser.name = \"Maemo\"}", id: "browser:maemo" },
{ label: "Browser Maxthon", pattern: "{$.payload.userAgent.browser.name = \"Maxthon\"}", id: "browser:maxthon" },
{ label: "Browser Midori", pattern: "{$.payload.userAgent.browser.name = \"Midori\"}", id: "browser:midori" },
{ label: "Browser Minimo", pattern: "{$.payload.userAgent.browser.name = \"Minimo\"}", id: "browser:minimo" },
{ label: "Browser MIUI Browser", pattern: "{$.payload.userAgent.browser.name = \"MIUI Browser\"}", id: "browser:miui:browser" },
{ label: "Browser [Mobile] Safari", pattern: "{$.payload.userAgent.browser.name = \"[Mobile] Safari\"}", id: "browser:[mobile]:safari" },
{ label: "Browser Mosaic", pattern: "{$.payload.userAgent.browser.name = \"Mosaic\"}", id: "browser:mosaic" },
{ label: "Browser Mozilla", pattern: "{$.payload.userAgent.browser.name = \"Mozilla\"}", id: "browser:mozilla" },
{ label: "Browser Netfront", pattern: "{$.payload.userAgent.browser.name = \"Netfront\"}", id: "browser:netfront" },
{ label: "Browser Netscape", pattern: "{$.payload.userAgent.browser.name = \"Netscape\"}", id: "browser:netscape" },
{ label: "Browser NetSurf", pattern: "{$.payload.userAgent.browser.name = \"NetSurf\"}", id: "browser:netsurf" },
{ label: "Browser Nokia", pattern: "{$.payload.userAgent.browser.name = \"Nokia\"}", id: "browser:nokia" },
{ label: "Browser OmniWeb", pattern: "{$.payload.userAgent.browser.name = \"OmniWeb\"}", id: "browser:omniweb" },
{ label: "Browser Opera [Mini/Mobi/Tablet]", pattern: "{$.payload.userAgent.browser.name = \"Opera [Mini/Mobi/Tablet]\"}", id: "browser:opera:[mini/mobi/tablet]" },
{ label: "Browser PhantomJS", pattern: "{$.payload.userAgent.browser.name = \"PhantomJS\"}", id: "browser:phantomjs" },
{ label: "Browser Phoenix", pattern: "{$.payload.userAgent.browser.name = \"Phoenix\"}", id: "browser:phoenix" },
{ label: "Browser Polaris", pattern: "{$.payload.userAgent.browser.name = \"Polaris\"}", id: "browser:polaris" },
{ label: "Browser QQBrowser", pattern: "{$.payload.userAgent.browser.name = \"QQBrowser\"}", id: "browser:qqbrowser" },
{ label: "Browser QQBrowserLite", pattern: "{$.payload.userAgent.browser.name = \"QQBrowserLite\"}", id: "browser:qqbrowserlite" },
{ label: "Browser Quark", pattern: "{$.payload.userAgent.browser.name = \"Quark\"}", id: "browser:quark" },
{ label: "Browser RockMelt", pattern: "{$.payload.userAgent.browser.name = \"RockMelt\"}", id: "browser:rockmelt" },
{ label: "Browser Silk", pattern: "{$.payload.userAgent.browser.name = \"Silk\"}", id: "browser:silk" },
{ label: "Browser Skyfire", pattern: "{$.payload.userAgent.browser.name = \"Skyfire\"}", id: "browser:skyfire" },
{ label: "Browser SeaMonkey", pattern: "{$.payload.userAgent.browser.name = \"SeaMonkey\"}", id: "browser:seamonkey" },
{ label: "Browser Sleipnir", pattern: "{$.payload.userAgent.browser.name = \"Sleipnir\"}", id: "browser:sleipnir" },
{ label: "Browser SlimBrowser", pattern: "{$.payload.userAgent.browser.name = \"SlimBrowser\"}", id: "browser:slimbrowser" },
{ label: "Browser Swiftfox", pattern: "{$.payload.userAgent.browser.name = \"Swiftfox\"}", id: "browser:swiftfox" },
{ label: "Browser Tizen", pattern: "{$.payload.userAgent.browser.name = \"Tizen\"}", id: "browser:tizen" },
{ label: "Browser UCBrowser", pattern: "{$.payload.userAgent.browser.name = \"UCBrowser\"}", id: "browser:ucbrowser" },
{ label: "Browser Vivaldi", pattern: "{$.payload.userAgent.browser.name = \"Vivaldi\"}", id: "browser:vivaldi" },
{ label: "Browser w3m", pattern: "{$.payload.userAgent.browser.name = \"w3m\"}", id: "browser:w3m" },
{ label: "Browser Waterfox", pattern: "{$.payload.userAgent.browser.name = \"Waterfox\"}", id: "browser:waterfox" },
{ label: "Browser WeChat", pattern: "{$.payload.userAgent.browser.name = \"WeChat\"}", id: "browser:wechat" },
{ label: "Browser Yandex", pattern: "{$.payload.userAgent.browser.name = \"Yandex\"}", id: "browser:yandex" }]


export const BrowsersAll = { label: "Browsers All", pattern: "{$.event = \"nx:dom:useragent\"}", id: "browser:all" }