import { IMetricsFilterAddon } from "."
import * as mappings from './marks'
/**
 * @desc 
 * @summary 
 * @requires clientsdk library on installed on client application to use this patterns.
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html
 **/

export const DeviceOS: IMetricsFilterAddon[] = [{ label: "All OS", metricFilter: { path: ["event"], value: mappings.MARK.SessionDataHardware }, id: "os:all" }]

// export const DeviceVendor: IMetricsFilterAddon[] =
//     [{ label: "Device Acer", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Acer" }, id: "device:acer" },
//     { label: "Device Alcatel", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Alcatel" }, id: "device:alcatel" },
//     { label: "Device Amazon", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Amazon" }, id: "device:amazon" },
//     { label: "Device Apple", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Apple" }, id: "device:apple" },
//     { label: "Device Archos", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Archos" }, id: "device:archos" },
//     { label: "Device Asus", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Asus" }, id: "device:asus" },
//     { label: "Device BenQ", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "BenQ" }, id: "device:benq" },
//     { label: "Device BlackBerry", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "BlackBerry" }, id: "device:blackberry" },
//     { label: "Device Dell", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Dell" }, id: "device:dell" },
//     { label: "Device GeeksPhone", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "GeeksPhone" }, id: "device:geeksphone" },
//     { label: "Device Google", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Google" }, id: "device:google" },
//     { label: "Device HP", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "HP" }, id: "device:hp" },
//     { label: "Device HTC", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "HTC" }, id: "device:htc" },
//     { label: "Device Huawei", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Huawei" }, id: "device:huawei" },
//     { label: "Device Jolla", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Jolla" }, id: "device:jolla" },
//     { label: "Device Lenovo", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Lenovo" }, id: "device:lenovo" },
//     { label: "Device LG", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "LG" }, id: "device:lg" },
//     { label: "Device Meizu", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Meizu" }, id: "device:meizu" },
//     { label: "Device Microsoft", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Microsoft" }, id: "device:microsoft" },
//     { label: "Device Motorola", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Motorola" }, id: "device:motorola" },
//     { label: "Device Nexian", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Nexian" }, id: "device:nexian" },
//     { label: "Device Nintendo", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Nintendo" }, id: "device:nintendo" },
//     { label: "Device Nokia", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Nokia" }, id: "device:nokia" },
//     { label: "Device Nvidia", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Nvidia" }, id: "device:nvidia" },
//     { label: "Device OnePlus", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "OnePlus" }, id: "device:oneplus" },
//     { label: "Device Ouya", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Ouya" }, id: "device:ouya" },
//     { label: "Device Palm", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Palm" }, id: "device:palm" },
//     { label: "Device Panasonic", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Panasonic" }, id: "device:panasonic" },
//     { label: "Device Pebble", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Pebble" }, id: "device:pebble" },
//     { label: "Device Polytron", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Polytron" }, id: "device:polytron" },
//     { label: "Device RIM", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "RIM" }, id: "device:rim" },
//     { label: "Device Samsung", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Samsung" }, id: "device:samsung" },
//     { label: "Device Sharp", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Sharp" }, id: "device:sharp" },
//     { label: "Device Siemens", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Siemens" }, id: "device:siemens" },
//     { label: "Device Sony[Ericsson]", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Sony[Ericsson]" }, id: "device:sony[ericsson]" },
//     { label: "Device Sprint", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Sprint" }, id: "device:sprint" },
//     { label: "Device Xbox", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Xbox" }, id: "device:xbox" },
//     { label: "Device Xiaomi", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "Xiaomi" }, id: "device:xiaomi" },
//     { label: "Device ZTE", metricFilter: { path: ["payload", "userAgent", "device", "vendor"], value: "ZTE" }, id: "device:zte" }]


// export const DeviceType: IMetricsFilterAddon[] = [
//     { id: "device:type:console", label: "console", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "console" } },
//     { id: "device:type:mobile", label: "mobile", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "mobile" } },
//     { id: "device:type:tablet", label: "tablet", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "tablet" } },
//     { id: "device:type:smarttv", label: "smarttv", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "smarttv" } },
//     { id: "device:type:wearable", label: "wearable", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "wearable" } },
//     { id: "device:type:embedded", label: "embedded", metricFilter: { path: ["payload", "userAgent", "device", "type"], value: "embedded" } }]

// export const DeviceOS: IMetricsFilterAddon[] =
//     [{ label: "OS AIX", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "AIX" }, id: "os:aix" },
//     { label: "OS Amiga OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Amiga OS" }, id: "os:amiga:os" },
//     { label: "OS Android", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Android" }, id: "os:android" },
//     { label: "OS Arch", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Arch" }, id: "os:arch" },
//     { label: "OS Bada", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Bada" }, id: "os:bada" },
//     { label: "OS BeOS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "BeOS" }, id: "os:beos" },
//     { label: "OS BlackBerry", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "BlackBerry" }, id: "os:blackberry" },
//     { label: "OS CentOS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "CentOS" }, id: "os:centos" },
//     { label: "OS Chromium OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Chromium OS" }, id: "os:chromium:os" },
//     { label: "OS Contiki,Fedora", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Contiki,Fedora" }, id: "os:contiki,fedora" },
//     { label: "OS Firefox OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Firefox OS" }, id: "os:firefox:os" },
//     { label: "OS FreeBSD", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "FreeBSD" }, id: "os:freebsd" },
//     { label: "OS Debian", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Debian" }, id: "os:debian" },
//     { label: "OS DragonFly", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "DragonFly" }, id: "os:dragonfly" },
//     { label: "OS Gentoo", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Gentoo" }, id: "os:gentoo" },
//     { label: "OS GNU", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "GNU" }, id: "os:gnu" },
//     { label: "OS Haiku", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Haiku" }, id: "os:haiku" },
//     { label: "OS Hurd", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Hurd" }, id: "os:hurd" },
//     { label: "OS iOS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "iOS" }, id: "os:ios" },
//     { label: "OS Joli", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Joli" }, id: "os:joli" },
//     { label: "OS Linpus", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Linpus" }, id: "os:linpus" },
//     { label: "OS Linux", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Linux" }, id: "os:linux" },
//     { label: "OS Mac OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Mac OS" }, id: "os:mac:os" },
//     { label: "OS Mageia", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Mageia" }, id: "os:mageia" },
//     { label: "OS Mandriva", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Mandriva" }, id: "os:mandriva" },
//     { label: "OS MeeGo", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "MeeGo" }, id: "os:meego" },
//     { label: "OS Minix", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Minix" }, id: "os:minix" },
//     { label: "OS Mint", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Mint" }, id: "os:mint" },
//     { label: "OS Morph OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Morph OS" }, id: "os:morph:os" },
//     { label: "OS NetBSD", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "NetBSD" }, id: "os:netbsd" },
//     { label: "OS Nintendo", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Nintendo" }, id: "os:nintendo" },
//     { label: "OS OpenBSD", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "OpenBSD" }, id: "os:openbsd" },
//     { label: "OS OpenVMS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "OpenVMS" }, id: "os:openvms" },
//     { label: "OS OS/2", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "OS/2" }, id: "os:os/2" },
//     { label: "OS Palm", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Palm" }, id: "os:palm" },
//     { label: "OS PC-BSD", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "PC-BSD" }, id: "os:pc-bsd" },
//     { label: "OS PCLinuxOS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "PCLinuxOS" }, id: "os:pclinuxos" },
//     { label: "OS Plan9", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Plan9" }, id: "os:plan9" },
//     { label: "OS Playstation", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Playstation" }, id: "os:playstation" },
//     { label: "OS QNX", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "QNX" }, id: "os:qnx" },
//     { label: "OS RedHat", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "RedHat" }, id: "os:redhat" },
//     { label: "OS RIM Tablet OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "RIM Tablet OS" }, id: "os:rim:tablet:os" },
//     { label: "OS RISC OS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "RISC OS" }, id: "os:risc:os" },
//     { label: "OS Sailfish", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Sailfish" }, id: "os:sailfish" },
//     { label: "OS Series40", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Series40" }, id: "os:series40" },
//     { label: "OS Slackware", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Slackware" }, id: "os:slackware" },
//     { label: "OS Solaris", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Solaris" }, id: "os:solaris" },
//     { label: "OS SUSE", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "SUSE" }, id: "os:suse" },
//     { label: "OS Symbian", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Symbian" }, id: "os:symbian" },
//     { label: "OS Tizen", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Tizen" }, id: "os:tizen" },
//     { label: "OS Ubuntu", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Ubuntu" }, id: "os:ubuntu" },
//     { label: "OS UNIX", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "UNIX" }, id: "os:unix" },
//     { label: "OS VectorLinux", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "VectorLinux" }, id: "os:vectorlinux" },
//     { label: "OS WebOS", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "WebOS" }, id: "os:webos" },
//     { label: "OS Windows [Phone/Mobile]", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Windows [Phone/Mobile]" }, id: "os:windows:[phone/mobile]" },
//     { label: "OS Zenwalk", metricFilter: { path: ["payload", "userAgent", "os", "name"], value: "Zenwalk" }, id: "os:zenwalk" }]
